language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: OidWOfiWriENk4KhvZV53YTWk5TazNTXq1BB4cqgEcL4ELLJIjF1SubiCZyFkx9IGmTTAB/RhzyJ92JToZkXzNIIjlOwT4Zn6+cSEdjF/5tGCYvhaaFOtCJLxoVFXHcxPanTOmTrr0rTvSak8Gp5glax8IF5eGLKwoYRn1gDQlI9z5mQAVwuTu/pM76zpZuLJwJia2cV4DmUjeA4j+oTK2WmObTKq4xqt+IDikYvUVCNPFQwgb0X05VnwbHMgNhcEL/pBuvxT1kLwwE/nh+xWfFn8/yE0XEC4PNQaxIaGLYgo6vT8miaV2SQxum2OZ88S2V/kgZXolpGGX89hCdeTN9GP0lNnyUabZ2l4Ya4RFgw5OK/NFTbVGGkG7eMsDBEvfewZ63n9nWGZ8aWbNEftK14qs42jp/T47zIqq0ZPBiASyF6ZTPLbp9fVoM4K0+Dmjco8/cj3G37KQ3NAWkEaKX+DR20c12eLqjMwNx/87T/IpBQBiWZkhOijCZ1h/lOP42mop4zl5dQgSzL4S9d5YVgs5YC8LJg/yh62uOuQMSVO+ZFNcZXZQGNrNdIZvfNUzvOXFDYhJWcEW2wGYj/nHznut4qjkZ4IyPQFQ/KwuGtqONuE8bioqFn1B/IAC25Qs2lesCGudXOcc+19e/GN90/s+hVhCXkAtlgjJ8rjcQ=
