language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: kRFIIoZ8S/EBKPTRXSd2ChUxDGLcGEBzdiUDsaaOF8QDG8d4xLI5AY40AYOjY6ESlcXxATZnsmfZnyP5Zfc6d36Dz/d26Ttk2eiTOY95vD6BToy4yp92mZS6ohWoTnq2pGAEJdRo2T+vuupMyh7SSXFXa6O6BmHqPpMNo/ljQwgrF/onMS5FjJu/fae5YD5j8Q98qo8lniG063Mp/+XzPNd6VUUJ4BjTaE7FzkmqVbB2ySoiM9vCMBI6kBRjTLa4qQQBE7qmHiVLH17iaZI4kLqszVLd1WTZtdi7UfV2v27Gb8qi7edn9PEIQCmNlRATadtrZ72NQkhqFw3wbqLYsRrbtR59pabJ65HvbMv9Uunnf/7KyLGxZOsh1wVG+OrKfmXYahgKeIwrlXZ/CMUn/KfPG5EyKI0rxxDTTWnRc0aAEJ4r4WJ6BUd9mVPmbqhSGn7xt8j4l1WSX0BynWTI1RfkNKZag86IfhORTNLMVNYbT9z+fKkyZfI2OMaC3N7lHZi7UdxKK/N88q7ownaMHD2VMYdp6nUVcpLKun6bN/Zdw7olmTVbSmBJbedg9wxkiytDFpUWS5Iq7fIft9kxH2qVRkpmD6twM2nzyhSN8vuUETC/S6hjnI+tUFLMmpqZW7tUNiIDk8M3aceD/b22AfPwhNL0Dd5I1IAfcmxNxfs=
