language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: alNl2iPIGmeT64tF9cfv7cyBj2HfistJPYgGs/E6gsneBtmHcyHCfq/HcceS1qKnJD3Ns3ApHk/gpWIfAC9g8TnAFElHbSOtwty2HY1OgJndUMfP7nD4BfR6rh1KHniymBGMoadjRwhmdpHexxpP1N274ATokfiDkOwP5Fu+B0Q51dZLWsp+aH3Nn/J5V0r2SURAmsiBcHcdWC2TmcKfEXLAK58PnnoV4NGWOmq+RgB2gVvqndU9jzuFjjvpfX0COVUYjFLbeHvxa7yQ/I6DObLrm454+m8/fYrgf2syzEsonpBRMJBPKy4MjTxFkmSHNOpifWgakmjMD2tssrkYduETFC1i48jE5CZDL2+0SxNRai7wnt093tEDEGK8JPEy6/kCIBI29mXva5Yo+hIJd6OzztE1JQNJu2V+GOA+0W4jxY6khIC0bEg2u+mGl85mlQnH71d+eajAgVlouRgXoUj/8BYpISqW8IJHdk6LWNSzPa/z9rmNeXioGathtlKdLwWBRXy0oYTiC2t5ZgZSdDTnzT5ZVKYVrHOZqTTEhwTBuva5dB2jJhe4is03jJIpsZz9s+6hec9no4LBgZPgV47rsZ3xGoE884xEAjSNPj4eCipD9O3M/k3zlEjWaAtcIS2/PeZ++lDtL+iU6xcdthj2LAbr3Gm+1MvR2PGBuac=
