language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: horse-battery-ek416
  api_key:
    secure: TPnudOjsSHJ6QzLagrWwlvccQ8QidD5/uQe5EkxCCMXl6MEowy0sNCGRNF2DRKa8Nmnz1aX7IC6LoHL2Tx5sdoquLVOu982wGMGDVfOklDC5jTSaJtpEpbcsHGVXVdQ6w+7jd1wJq+vbeKtgN1YyXBn/ATcyhereB55N9rdQ/n3w5qY5peEj8EndTCXopWAwXb9At2CBYhhy7hbBjk/6TAljzDVWBoRMGggNQmrdLZL9yt+AMw4WSAnadea8+kdNxY8FEOyuJAc9QoIUFbYA0vioEDei5RYPliFr2PPW5XztvYqjnUZe5EP7SPLPCq/uP6e2HpyxM00Sz+uNIHm4VuSE5TJvoiNMFSKyqKORC0y0MIdVL7wBYdjMEgx4R+YNzBe3bcrNmY//1XtutLZRSqaZkmFb+FU77/fHf7rdoYHDjxNzhqrsRLwYn+Y0hiw1gYtw2BCakRL13NdnVZ3DtH5SwtjxPYgKyFVzh2IrUJJU3kTFFQwbt1+qfi+f3/3t0op57R1Ui7BdHlJhdZzDoyx2OusBvX+OZDShh3j1Np6quh6KVFoRsSuGVNhj6+GQwwgLsXG2RzNfn0OhwdMEDqQYR59OP7W7tAMwSA11kdseLJU5C8w2PuL9Rlxqbh9zQn4BfG2NugBrsOwCyuhrc/UFNC4z0cWv+sq4bQGVQ+A=
