language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: Ti8QTvVQp0jZyKtK+fHjvNp5/usSt0iMdbDaliqYM7S1iOf5GYEmr/F3HSwY5BfYKHXo8idIUbdbabriL6CwnY5DoL454QBQLjdTk7XRk2UNpHb5AHZB3rhwSuTJMrls1WJk1U2qIZoFijrWP7HWw/yh33bmWdRy7/6ZpYYZ+Se+nMJr8Vf11AMh9Vw2xLYD1DuRwfPtBDkgLL9hBvVngDExx+57nCJgL3Bz+amatLZYebiZ6JWrCbvYBhBLeFmxYcfaJB7X3D/Li2RGVF9Hm9WqryoXJ8pvI1ae6ebI7YWgM/nOFFZliJ4iDO2ZmbgZeNR3ReiFiijLl8KfbjXHXbJ2QVAdyPxXK/4i46h924OPGN6pmuCwjYKXpxOD/P8iVIJ9025X11fyy7j8BxjGobbDPNZtDRe8I1M65WSw56E+vVNkSBTtQ/yDxGt2LnNJKxUi8paYDKMyIENUezoe06DzxDOMef1BifUklnCNk6tx019/EdsYmCKd4M7Dc95PfQnDNxDiCEhsd0Oz77wuprk7KCqLVZ0JOlPVJkbdjIEozrfXrXGs2JwD62K+ZL4rKMQyE+TU7c1Ev6myz4jYW3MomRx1WINF2u17hPumao3X7XzIe4CrZWDFlKOI0iTfoBL/XsNi86awDJir/7GS8t/DuSxsizAbfFKzlDCTlSQ=
