language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: b5OcrBwkDNCkQz/1Fa10b6D7Iq+Krjfw7cNx1+9lr1qrF+t8YHSUjVJ5B/akJ9da8k7DmiqaV43kYv0uLgmj0I1Ds7PN3MHQg0GIvuy10VNJ8PQMMrM43v5cy2U59kB//ROitDpV1IMo+F5wgCTBZFt6Grcvww8gRGuaXmSHpWh9LPTZJRclxywex7crMls/1DaHsezZQj29vtFFlRJkMiFbSlShspb1APAtfdFGrItb3yTcp8RgN/brTY4P7RktG7c1CgS67gZPTywPZBTs9mZwBRT33lgLL1zslURJZ91LSqgLygzr+5wHodutcmv5cwicZOESv1EIlWXDGkYUMnZp3XCEfD7+sz2jUkgDgXHjcT+3EsSBTjfuBh2WUFxkxT38hK1RDFDCIGwV/DntItbU3eE9Sr3ez/5ZhGRs+59nm2vhES5FcVx34MboakZkNweOQCxhlnMCwxgSTlut+3z3KF1qIrxJIUSuJQXVvdkJVHWSoZb7RHRH2Rwg7PzPxfGHV72MZHge83d2XPfOoNpWIg3FsqxczfwJtnP5nu+wGXQ1EB5cWiNL4HGfhhIHbpBG5/vKa6cLSU08wjpJh+b+ZtmhniR3vnlANQp1iNaIl57krcc7dkmZTCZUrzqH1B/H/W1gUCbDfnguNckey/TYs6HBFzwAq7SNkjkJ35w=
